INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(50, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', NULL, '1 Colorless', 43, 1, 5, 1),
(60, 'Kadabra', 'Psi Pokémon', 'Recover', NULL, 'Psychic', NULL, '2 Colorless', 32, 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', NULL, '3 Colorless', 1, 1, 5, 3),
(40, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', NULL, '1 Colorless', 50, 1, 5, 1),
(70, 'Gengar', 'Shadow Pokémon', 'Nightmare', '10', 'Psychic', NULL, '2 Colorless', 5, 1, 5, 2),
(60, 'Drowzee', 'Hypnosis Pokémon', 'Pound', '10', 'Psychic', NULL, '1 Colorless', 49, 1, 5, 1),
(70, 'Hypno', 'Hypnosis Pokémon', 'Prophecy', NULL, 'Psychic', NULL, '2 Colorless', 8, 2, 5, 2),
(50, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Lightning', NULL, '1 Colorless', 59, 1, 3, 1),
(60, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', NULL, 'Lightning', NULL, '2 Colorless', 36, 1, 3, 2),
(90, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Lightning', NULL, '3 Colorless', 13, 1, 3, 3),
(70, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Lightning', NULL, '1 Colorless', 60, 3, 3, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', NULL, 'Lightning', NULL, '2 Colorless', 24, 3, 3, 2),
(60, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Lightning', NULL, '1 Colorless', 48, 3, 3, 1),
(80, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Lightning', NULL, '2 Colorless', 22, 3, 3, 2),
(90, 'Magikarp', 'Fish Pokémon', 'Tackle', '10', 'Lightning', NULL, '1 Colorless', 61, 1, 3, 1),
(100, 'Gyarados', 'Atrocious Pokémon', 'Dragon Rage', '50', 'Lightning', NULL, '3 Colorless', 6, 1, 3, 2),
(70, 'Onix', 'Rock Snake Pokémon', 'Rock Throw', '10', 'Grass', NULL, '3 Colorless', 56, 1, 6, 1),
(90, 'Chansey', 'Egg Pokémon', 'Scrunch', NULL, 'Fighting', NULL, '1 Colorless', 3, 1, 11, 1),
(80, 'Clefairy', 'Fairy Pokémon', 'Sing', NULL, 'Fighting', NULL, '1 Colorless', 5, 1, 11, 1),
(100, 'Clefable', 'Fairy Pokémon', 'Metronome', NULL, 'Fighting', NULL, '2 Colorless', 1, 2, 11, 2);
