INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Bulbasaur', 'Seed Pokémon', 'Leech Seed', '20', 'Fire', NULL, '1 Colorless', 44, 1, 1, 1),
(50, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', NULL, '1 Colorless', 46, 1, 2, 1),
(40, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '10', 'Lightning', NULL, '1 Colorless', 63, 1, 3, 1),
(40, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', NULL, '1 Colorless', 58, 1, 4, 1),
(60, 'Haunter', 'Gas Pokémon', 'Hypnosis', NULL, 'Psychic', NULL, '1 Colorless', 29, 1, 5, 2),
(80, 'Ivysaur', 'Seed Pokémon', 'Vine Whip', '30', 'Fire', NULL, '2 Colorless', 30, 1, 1, 2),
(90, 'Charmeleon', 'Flame Pokémon', 'Slash', '30', 'Water', NULL, '2 Colorless', 24, 1, 2, 2),
(70, 'Wartortle', 'Turtle Pokémon', 'Withdraw', NULL, 'Lightning', NULL, '1 Colorless', 42, 1, 3, 2),
(120, 'Venusaur', 'Seed Pokémon', 'Solarbeam', '60', 'Fire', NULL, '2 Colorless', 15, 1, 1, 3),
(120, 'Charizard', 'Flame Pokémon', 'Fire Spin', '100', 'Water', NULL, '3 Colorless', 4, 1, 2, 3),
(100, 'Blastoise', 'Shellfish Pokémon', 'Hydro Pump', '40+', 'Lightning', NULL, '3 Colorless', 2, 1, 3, 3),
(70, 'Jigglypuff', 'Balloon Pokémon', 'Lullaby', NULL, 'Fighting', NULL, '1 Colorless', 54, 2, 11, 1),
(90, 'Wigglytuff', 'Balloon Pokémon', 'Do the Wave', '10+', 'Fighting', NULL, '2 Colorless', 32, 2, 11, 2),
(60, 'Eevee', 'Evolution Pokémon', 'Quick Attack', '10+', 'Fighting', NULL, '1 Colorless', 51, 2, 11, 1),
(70, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', NULL, '1 Colorless', 10, 2, 1, 1),
(100, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '30', 'Fighting', NULL, '4 Colorless', 11, 2, 11, 1),
(60, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '20', 'Grass', NULL, '1 Colorless', 43, 3, 6, 1),
(90, 'Kabutops', 'Shellfish Pokémon', 'Slash', '30', 'Grass', NULL, '2 Colorless', 9, 3, 6, 2),
(80, 'Aerodactyl', 'Fossil Pokémon', 'Wing Attack', '30', 'Lightning', NULL, '2 Colorless', 1, 3, 11, 1),
(70, 'Lapras', 'Transport Pokémon', 'Water Gun', '10+', 'Lightning', NULL, '2 Colorless', 10, 3, 3, 1);
