INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(50, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', NULL, '1 Colorless', 45, 1, 1, 1),
(60, 'Metapod', 'Cocoon Pokémon', 'Stiffen', NULL, 'Fire', NULL, '2 Colorless', 54, 1, 1, 2),
(80, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', NULL, '1 Colorless', 33, 1, 1, 3),
(50, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', NULL, '1 Colorless', 69, 1, 1, 1),
(60, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', NULL, 'Fire', NULL, '2 Colorless', 33, 1, 1, 2),
(80, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', NULL, '1 Colorless', 17, 1, 1, 3),
(70, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', NULL, '1 Colorless', 55, 1, 1, 1),
(80, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', NULL, '2 Colorless', 36, 1, 1, 2),
(90, 'Nidoqueen', 'Drill Pokémon', 'Boyfriends', '20+', 'Psychic', NULL, '3 Colorless', 12, 1, 1, 3),
(70, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Hazard', '30', 'Psychic', NULL, '1 Colorless', 56, 1, 1, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', NULL, '2 Colorless', 37, 1, 1, 2),
(90, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', NULL, '3 Colorless', 11, 1, 1, 3),
(60, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', NULL, '1 Colorless', 58, 2, 1, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', NULL, '2 Colorless', 32, 2, 1, 2),
(80, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', NULL, '2 Colorless', 15, 2, 1, 3),
(50, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', NULL, '1 Colorless', 57, 2, 1, 1),
(70, 'Parasect', 'Mushroom Pokémon', 'Spore', NULL, 'Fire', NULL, '2 Colorless', 34, 2, 1, 2),
(60, 'Exeggcute', 'Egg Pokémon', 'Hypnosis', NULL, 'Fire', NULL, '1 Colorless', 52, 2, 1, 1),
(80, 'Exeggutor', 'Coconut Pokémon', 'Big Eggsplosion', '20x', 'Fire', NULL, '3 Colorless', 35, 2, 1, 2),
(70, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '10', 'Fighting', NULL, '1 Colorless', 56, 2, 11, 1),
(90, 'Persian', 'Classy Cat Pokémon', 'Scratch', '20', 'Fighting', NULL, '1 Colorless', 36, 2, 11, 2),
(60, 'Rhyhorn', 'Spikes Pokémon', 'Horn Attack', '30', 'Grass', NULL, '2 Colorless', 61, 2, 6, 1),
(100, 'Rhydon', 'Drill Pokémon', 'Horn Drill', '50', 'Grass', NULL, '3 Colorless', 45, 2, 6, 2),
(70, 'Tauros', 'Wild Bull Pokémon', 'Stomp', '20+', 'Fighting', NULL, '2 Colorless', 60, 2, 11, 1),
(80, 'Kangaskhan', 'Parent Pokémon', 'Fetch', NULL, 'Fighting', NULL, '3 Colorless', 5, 2, 11, 1),
(60, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Lightning', NULL, '1 Colorless', 48, 2, 11, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Lightning', NULL, '1 Colorless', 34, 2, 11, 2),
(70, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '30', 'Psychic', NULL, '1 Colorless', 7, 2, 6, 1),
(70, 'Hitmonchan', 'Punching Pokémon', 'Special Punch', '40', 'Psychic', NULL, '2 Colorless', 7, 1, 6, 1),
(60, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', NULL, '1 Colorless', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', NULL, '2 Colorless', 34, 1, 6, 2),
(100, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', NULL, '3 Colorless', 8, 1, 6, 3),
(60, 'Geodude', 'Rock Pokémon', 'Tackle', '10', 'Grass', NULL, '1 Colorless', 36, 3, 6, 1),
(80, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', NULL, '2 Colorless', 37, 3, 6, 2),
(100, 'Golem', 'Megaton Pokémon', 'Selfdestruct', '100', 'Grass', NULL, '4 Colorless', 18, 3, 6, 3),
(70, 'Omanyte', 'Spiral Pokémon', 'Water Gun', '10+', 'Grass', NULL, '1 Colorless', 40, 3, 3, 1),
(90, 'Omastar', 'Spiral Pokémon', 'Spike Cannon', '30x', 'Grass', NULL, '2 Colorless', 22, 3, 3, 2),
(70, 'Zubat', 'Bat Pokémon', 'Supersonic', NULL, 'Psychic', NULL, '1 Colorless', 57, 3, 5, 1),
(90, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', NULL, '2 Colorless', 21, 3, 5, 2);
